### ISSUE TITLE
Refreshing Access Token?

### ISSUE THREAD

**Issue by johanstenberg92** [oyediyildiz/scala-oauth2-provider-example#2]
First, thanks for a sample project!

Second,

Isn't this line a bit wierd?

https://github.com/oyediyildiz/scala-oauth2-provider-example/blob/master/app/oauth/MyDataHandler.scala#L37

Shouldn't you use the refresh-token?

**Comment by oyediyildiz** [comment]
Yes, you're right.  The refresh token should be validated first.  By the way, I don't intend to fix anything in this code :)
